export const ALGOLIA_APP_ID = process.env.REACT_APP_ALGOLIA_APP_ID
export const ALGOLIA_API_KEY = process.env.REACT_APP_ALGOLIA_API_KEY
export const OPEN_WEATHER_API_KEY = process.env.REACT_APP_OPEN_WEATHER_API_KEY